version: '3.8'

services:
  app:
    build: .
    command: python run_consuming.py
    volumes:
      - .:/app
    ports:
      - "5672:5672"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - PYTHONPATH=/app/
